Add versions to image archives and record archives in metadata
- Appending versions to archives file names, this makes image clean-up possible.
- Record image archives with a metadata file. When preloading a node, it's easier
  to get what's included in an ISO. e.g.:
    ```
    $ cat /srv/www/htdocs/harvester/iso/bundle/metadata.yaml
    images:
      common:
        - list: /harvester/images/rancher-images-v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head.txt
          archive: /harvester/images/rancher-images-v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head.tar.zst
        - list: /harvester/images/harvester-images-b62f9f8-dirty.txt
          archive: /harvester/images/harvester-images-b62f9f8-dirty.tar.zst
        - list: /harvester/images/harvester-repo-images-b62f9f8-dirty.txt
          archive: /harvester/images/harvester-repo-images-b62f9f8-dirty.tar.zst
      rke2:
        - list: /harvester/images/rke2-images.linux-amd64-v1.21.5-rke2r1.txt
          archive: /harvester/images/rke2-images.linux-amd64-v1.21.5-rke2r1.tar.zst
        - list: /harvester/images/rke2-images-multus.linux-amd64-v1.21.5-rke2r1.txt
          archive: /harvester/images/rke2-images-multus.linux-amd64-v1.21.5-rke2r1.tar.zst
      agent:
        - list: /rancherd/images/rancherd-bootstrap-images-b62f9f8-dirty.txt
          archive: /rancherd/images/rancherd-bootstrap-images-b62f9f8-dirty.tar.zst

    ```

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

diff --git a/package/harvester-os/files/usr/sbin/harv-install b/package/harvester-os/files/usr/sbin/harv-install
--- a/package/harvester-os/files/usr/sbin/harv-install
+++ b/package/harvester-os/files/usr/sbin/harv-install
@@ -116,7 +116,12 @@ preload_rke2_images()
       trap "rm -rf $inst_tmp" exit
 
       # extract rke2 tarball from image
-      rke2_image=$(grep 'docker.io/rancher/system-agent-installer-rke2:' /var/lib/rancher/agent/images/rancherd-bootstrap-images.txt)
+      image_list=$(ls /var/lib/rancher/agent/images/rancherd-bootstrap-images-*.txt | head -n 1)
+      if [ -z "$image_list" ]; then
+        echo "[ERROR] Fail to get rancherd bootstrap images list."
+        exit 1
+      fi
+      rke2_image=$(grep 'docker.io/rancher/system-agent-installer-rke2:' $image_list)
       wharfie --images-dir /var/lib/rancher/agent/images/ $rke2_image $inst_tmp
 
       # extract rke2 binary
