Deactivate LVM and MD devices before installation
If the target device is occupied, the partitioning could fail.

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
(cherry picked from commit c66449f3b4c19312984b12de37decb9a26d8d4d8)

diff --git a/package/harvester-os/files/usr/sbin/harv-install b/package/harvester-os/files/usr/sbin/harv-install
--- a/package/harvester-os/files/usr/sbin/harv-install
+++ b/package/harvester-os/files/usr/sbin/harv-install
@@ -369,6 +369,10 @@ if [ -L "$ELEMENTAL_TARGET" ]; then
   install_device=$(readlink -f "$ELEMENTAL_TARGET")
 fi
 
+# Tear down LVM and MD devices on the system, if the installing device is occuipied, the
+# partitioning operation could fail later. Be forgiven here.
+blkdeactivate --lvmoptions wholevg,retry --dmoptions force,retry --errors || true
+
 clear_disk_label
 
 # Run elemental installer but do not let it fetch ISO and do not shutdown
