Bump rancher-monitoring to 103.0.3+up45.31.1
Signed-off-by: Jian Wang <w13915984028@gmail.com>

diff --git a/scripts/hack/patch-rancher-monitoring-crd b/scripts/hack/patch-rancher-monitoring-crd
--- a/scripts/hack/patch-rancher-monitoring-crd
+++ b/scripts/hack/patch-rancher-monitoring-crd
@@ -33,6 +33,21 @@ patch_rancher_monitoring_crd_chart()
   echo "patched file"
   ls -alth "$origfile"
 
+  # replace shell image version; yq can also work, but it strips all blank lines; use patch instead
+  #  yq -e e '(.image | select(.repository == "rancher/shell") | .tag) = "v0.1.22"' -i ran-mon-crd-values.yaml
+  local valuesfile="./rancher-monitoring-crd/values.yaml"
+  local difffile="${pkg_monitoring_crd_path}/${monitoring_version}/patch-values-shell-version.diff"
+  echo "patch rancher/shell image version"
+  echo "the current values.yaml has following shell image version"
+  grep "rancher/shell" $valuesfile -1 || true
+  if [ -f "$difffile" ]; then
+    patch $valuesfile $difffile
+  else
+    echo "diff file $difffile is not found"
+  fi
+  echo "the patched values.yaml has following shell image version"
+  grep "rancher/shell" $valuesfile -1 || true
+
   # remove existing chart
   rm -f ${chart_dir}/rancher-monitoring-crd-${monitoring_version}.tgz
 
