Add version.yaml
Signed-off-by: Frank Yang <poan.yang@suse.com>

diff --git a/scripts/package-harvester-os b/scripts/package-harvester-os
--- a/scripts/package-harvester-os
+++ b/scripts/package-harvester-os
@@ -74,3 +74,25 @@ xorriso -osirrox on -indev ${ARTIFACTS_DIR}/${ISO_PREFIX}.iso -extract /rootfs.s
 cd ${ARTIFACTS_DIR}
 CHECKSUM_FILE=${ISO_PREFIX}.sha512
 sha512sum ${PROJECT_PREFIX}* > $CHECKSUM_FILE
+
+ISO_CHECKSUM=$(awk -viso_name="${ISO_PREFIX}.iso" '$2~iso_name{print $1}' $CHECKSUM_FILE)
+if [ -z "$ISO_CHECKSUM" ]; then
+  echo "Fail to find Harvester ISO file checksum."
+  exit 1
+fi
+
+# Write version.yaml
+if [[ -n "${DRONE_TAG}" ]]; then
+	RELEASE_DATE=$(date +'%Y%m%d')
+	cat > version.yaml <<EOF
+apiVersion: harvesterhci.io/v1beta1
+kind: Version
+metadata:
+  name: ${VERSION}
+  namespace: harvester-system
+spec:
+  isoChecksum: ${ISO_CHECKSUM}
+  isoURL: https://releases.rancher.com/harvester/${VERSION}/${ISO_PREFIX}.iso
+  releaseDate: ${RELEASE_DATE}
+EOF
+fi
